version: '3.7'
services:
  zookeeper-service:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      HOSTNAME_COMMAND: echo kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://_{HOSTNAME_COMMAND}:9092
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "messages:1:4"
    depends_on:
      - zookeeper-service
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    command: ["redis-server" , "/etc/redis/redis.conf" ]
    volumes:
      - ./redis:/etc/redis/
  redis-ui:
    image: marian/rebrow
    ports:
      - '5001:5001'
  
